/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.pharmacymanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author chand
 */
public class Agent extends javax.swing.JFrame {

    /**
     * Creates new form Medicine
     */
    public Agent() {
        initComponents();
        dbconnection();
        SelectAgent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Connection Con = null;
    Statement St = null, St1 = null;
    ResultSet Rs = null, Rs1 = null;

    @SuppressWarnings("unchecked")

    public void SelectAgent() {
        try {
            Con=dbconnection();
            St1 = Con.createStatement();
            Rs1 = St1.executeQuery("SELECT * FROM USER1.AGENTTABLE");
            AgentTable.setModel(DbUtils.resultSetToTableModel(Rs1));
            Con.close();

        } catch (Exception ex) {
            //Logger.getLogger(Medicine.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }

    public void cleartext() {
        AId.setText("");
        AName.setText("");
        AAge.setText("");
        APhone.setText("");
        APassword.setText("");
        AGender.setSelectedIndex(0);
    }
    
    public Connection dbconnection(){
        Connection Con1= null;
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver")/*.newInstance()*/;
            String path = System.getProperty("user.dir")+"/../PHARMADATABASE";
            Con1= DriverManager.getConnection("jdbc:derby:"+path, "User1", "1234");
        } catch (Exception ex) {
              System.out.println(ex.getMessage());
        }
        return Con1;
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        AGender = new javax.swing.JComboBox<>();
        AId = new javax.swing.JTextField();
        AName = new javax.swing.JTextField();
        AAge = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AgentTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        APhone = new javax.swing.JTextField();
        APassword = new javax.swing.JTextField();
        SellingLabel = new javax.swing.JLabel();
        MedicineLabel = new javax.swing.JLabel();
        CompanyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 155));
        jLabel4.setText("ID*");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 155));
        jLabel5.setText("Manage Agent");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 155));
        jLabel6.setText("Name* ");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 155));
        jLabel7.setText("Age*");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 155));
        jLabel9.setText("Password*");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 155));
        jLabel10.setText("Phone* ");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 155));
        jLabel11.setText("Gender*");

        AGender.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        AGender.setForeground(new java.awt.Color(0, 0, 155));
        AGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Male", "Female" }));
        AGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGenderActionPerformed(evt);
            }
        });

        AId.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        AId.setForeground(new java.awt.Color(0, 0, 155));

        AName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        AName.setForeground(new java.awt.Color(0, 0, 155));

        AAge.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        AAge.setForeground(new java.awt.Color(0, 0, 155));

        Add.setBackground(new java.awt.Color(255, 255, 255));
        Add.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Add.setForeground(new java.awt.Color(0, 0, 153));
        Add.setText("Add");
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });

        Update.setBackground(new java.awt.Color(255, 255, 255));
        Update.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Update.setForeground(new java.awt.Color(0, 0, 153));
        Update.setText("Update");
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(255, 255, 255));
        Delete.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Delete.setForeground(new java.awt.Color(0, 0, 153));
        Delete.setText("Delete");
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        AgentTable.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        AgentTable.setForeground(new java.awt.Color(0, 0, 155));
        AgentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Agent Id", "Agent Name", "Agent Age", "Agent Ph.", "Agent Passl", "Agent Gender"
            }
        ));
        AgentTable.setRowHeight(25);
        AgentTable.setSurrendersFocusOnKeystroke(true);
        AgentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AgentTable);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 155));
        jLabel12.setText("Agent List");

        APhone.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        APhone.setForeground(new java.awt.Color(0, 0, 155));
        APhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APhoneActionPerformed(evt);
            }
        });

        APassword.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        APassword.setForeground(new java.awt.Color(0, 0, 155));
        APassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AId, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AAge, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                        .addComponent(AName)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5)
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(APassword)
                        .addComponent(APhone)
                        .addComponent(AGender, 0, 165, Short.MAX_VALUE))
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(205, 205, 205))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10)
                                    .addComponent(APhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(APassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(AGender, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(AId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AAge, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Add)
                            .addComponent(Update)
                            .addComponent(Delete))
                        .addGap(64, 64, 64)))
                .addComponent(jLabel12)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        jLabel12.getAccessibleContext().setAccessibleName("");

        SellingLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        SellingLabel.setForeground(new java.awt.Color(240, 240, 240));
        SellingLabel.setText("Selling");
        SellingLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellingLabelMouseClicked(evt);
            }
        });

        MedicineLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        MedicineLabel.setForeground(new java.awt.Color(240, 240, 240));
        MedicineLabel.setText("Medicine");
        MedicineLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicineLabelMouseClicked(evt);
            }
        });

        CompanyLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        CompanyLabel.setForeground(new java.awt.Color(240, 240, 240));
        CompanyLabel.setText("Company");
        CompanyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompanyLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MedicineLabel)
                    .addComponent(SellingLabel)
                    .addComponent(CompanyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(47, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(MedicineLabel)
                        .addGap(18, 18, 18)
                        .addComponent(CompanyLabel)
                        .addGap(18, 18, 18)
                        .addComponent(SellingLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        SellingLabel.getAccessibleContext().setAccessibleName("ManuFacture");

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AGenderActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void APhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_APhoneActionPerformed

    private void APasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_APasswordActionPerformed

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked

        try {
            Con=dbconnection();
            PreparedStatement add = Con.prepareStatement("insert into AGENTTABLE Values(?,?,?,?,?,?)");
            add.setInt(1, Integer.valueOf(AId.getText()));
            add.setString(2, AName.getText());
            add.setInt(3, Integer.valueOf(AAge.getText()));
            add.setString(4, APhone.getText());
            add.setString(5, APassword.getText());
            add.setString(6, AGender.getSelectedItem().toString());
            int row = add.executeUpdate();
            JOptionPane.showMessageDialog(this, "Agent Successfully Added.");
            Con.close();
            SelectAgent();
            cleartext();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "ID should be unique.");
        }
    }//GEN-LAST:event_AddMouseClicked

    private void AgentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgentTableMouseClicked
        try {
            DefaultTableModel model = (DefaultTableModel) AgentTable.getModel();
            int MyIndex = AgentTable.getSelectedRow();
            AId.setText(model.getValueAt(MyIndex, 0).toString());
            AName.setText(model.getValueAt(MyIndex, 1).toString());
            AAge.setText(model.getValueAt(MyIndex, 2).toString());
            APhone.setText(model.getValueAt(MyIndex, 3).toString());
            APassword.setText(model.getValueAt(MyIndex, 4).toString());
            AGender.setSelectedItem(model.getValueAt(MyIndex, 5).toString());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_AgentTableMouseClicked

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        if (AId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select Agent to Delete.");
        } else {
            try {
                Con=dbconnection();
                String Id = AId.getText();
                String Querry = "DELETE FROM USER1.AGENTTABLE WHERE AID=" + Id;
                Statement Delete = Con.createStatement();
                Delete.execute(Querry);
                JOptionPane.showMessageDialog(this, "Agent Successfully Deleted.");
                SelectAgent();
                cleartext();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_DeleteMouseClicked

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        if (AId.getText().isEmpty() || AName.getText().isEmpty() || AAge.getText().isEmpty() || APhone.getText().isEmpty() || APassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select Agent to Update.");
        } else {
            try {
                Con=dbconnection();
                String Id = AId.getText();
                String Querry = "UPDATE USER1.AGENTTABLE SET ANAME='" + AName.getText() + "',AAGE=" + AAge.getText() + ",APHONE='" + APhone.getText() + "',APASSWORD='" + APassword.getText() + "',AGENDER='" + AGender.getSelectedItem() + "' WHERE AID=" + Id;
                Statement Update = Con.createStatement();
                Update.execute(Querry);
                JOptionPane.showMessageDialog(this, "Agent Successfully Updated.");
                SelectAgent();
                cleartext();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_UpdateMouseClicked

    private void MedicineLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicineLabelMouseClicked
        new Medicine().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MedicineLabelMouseClicked

    private void CompanyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompanyLabelMouseClicked
        new Company().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CompanyLabelMouseClicked

    private void SellingLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellingLabelMouseClicked
        new Selling().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SellingLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AAge;
    private javax.swing.JComboBox<String> AGender;
    private javax.swing.JTextField AId;
    private javax.swing.JTextField AName;
    private javax.swing.JTextField APassword;
    private javax.swing.JTextField APhone;
    private javax.swing.JButton Add;
    private javax.swing.JTable AgentTable;
    private javax.swing.JLabel CompanyLabel;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel MedicineLabel;
    private javax.swing.JLabel SellingLabel;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
